# Generated by Django 5.0.3 on 2026-03-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract'),
    ]

    operations = [
        # This is the "Magic" command that activates the extension
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector;'),
    ]
