# Generated by Django 5.0.3 on 2026-03-24 19:58

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_enable_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('chunk_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='contracts.contract')),
            ],
            options={
                'indexes': [models.Index(fields=['contract', 'chunk_index'], name='contracts_c_contrac_3bdd4d_idx')],
            },
        ),
    ]
