# Generated by Django 5.0.3 on 2026-03-24 20:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
