name: Django CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Dummy Env for CI
        # CI needs these variables to start the Django container
        run: |
          echo "DATABASE_URL=postgres://admin:password123@db:5432/contractiq" > .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "GEMINI_API_KEY=mock_key_for_testing" >> .env

      - name: Build and Start Stack
        run: docker compose up --build -d

      - name: Wait for services
        run: |
          echo "Waiting 20 seconds for DB and Redis to stabilize..."
          sleep 20
          docker compose ps
          docker compose logs web

      - name: Run Migrations
        run: docker compose exec web python manage.py migrate

      - name: Initialize Redis Vector Index
        run: docker compose exec web python manage.py setup_vectors

      - name: Run Unit Tests
        run: docker compose exec web python manage.py test contracts

      - name: Cleanup
        if: always()
        run: docker compose down